#To Change from /camel to / in url
camel:
  springboot:
    name: Middleware-AccountAPIs
  servlet:
    mapping:
      context-path: /*
  rest:
    context-path: /
    
server:
  port: 8081
  
UDDIConnector:
  host : ${UDDI_HOST}
  contextPath : ${UDDI_CONTEXTPATH}